### ISSUE TITLE
راهنمایی و همکاری

### ISSUE THREAD

**Issue by mohammadinia1** [FatemehAhsan/CRYSTALS-Dilithium_Key-Generation_Verilog#1]
سلام و عرض ادب.
من دانشجوی ارشد در امنیت شبکه هستم.
به مطالعات شما درباره رمز نگاری والگوریتم رمزنگاری کریستال دلیتیوم علاقه مند شدم.
بسیار مایلم با شما بصورت آنلاین صحبتی داشته باشم.
ممنونم.

**Comment by FatemehAhsan** [comment]
سلام.
می‌توانید برای هماهنگی به آدرس fteme.ahsan@gmail.com، ایمیل بفرستید.
